### ISSUE TITLE
little lock indicator

### ISSUE THREAD

**Issue by kajdo** [andreasgrafen/ag.proton#2]
Hi,

I really like your css and use it currently :) .... but there is one thing I'm missing and I don't know how to bring it back -- the lock indicator in the URL bar to see if I use HTTPS + reach the certificate information of the page when double-clicked.

could you give me a hint how to bring it back?

thx

**Comment by andreasgrafen** [comment]
Hi,

thank you very much. Glad you're liking the theme. To get the Security Indicator back just remove [line 201](https://github.com/andreasgrafen/ag.proton/blob/main/userChrome.css#L201) from the CSS. c:

I should probably put that together with all the other icon rules to make things a little more clear.

**Comment by kajdo** [comment]
thx!!

**Comment by andreasgrafen** [comment]
@kajdo – It should be visible by default in the V2 rewrite as well. c:
